import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
	NODE_ENV: process.env.NODE_ENV,
	PORT: process.env.PORT,
	DATABASE_URL: process.env.DATABASE_URL,
	BACKEND_URL: process.env.BACKEND_URL,
	FRONTEND_URL: process.env.FRONTEND_URL,
	BCRYPT_SALT_ROUNDS: process.env.BCRYPT_SALT_ROUNDS,
	JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET!,
	JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET!,
	JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN!,
	JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN!,
	GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,

	SUPER_ADMIN_NAME: process.env.SUPER_ADMIN_NAME!,
	SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL!,
	SUPER_ADMIN_PASSWORD: process.env.SUPER_ADMIN_PASSWORD!,

	TESTER_ADMIN_NAME: process.env.TESTER_ADMIN_NAME!,
	TESTER_ADMIN_EMAIL: process.env.TESTER_ADMIN_EMAIL!,
	TESTER_ADMIN_PASSWORD: process.env.TESTER_ADMIN_PASSWORD!,

	TESTER_DOCTOR_NAME: process.env.TESTER_DOCTOR_NAME!,
	TESTER_DOCTOR_EMAIL: process.env.TESTER_DOCTOR_EMAIL!,
	TESTER_DOCTOR_PASSWORD: process.env.TESTER_DOCTOR_PASSWORD!,

	REDIS_HOST: process.env.REDIS_HOST!,
	REDIS_PORT: process.env.REDIS_PORT!,
	REDIS_USERNAME: process.env.REDIS_USERNAME!,
	REDIS_PASSWORD: process.env.REDIS_PASSWORD!,
};
